name: Build

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Build Windows
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Cache CMake dependency source code
              uses: actions/cache@v4
              env:
                  cache-name: cache-cmake-dependency-sources
              with:
                  path: ${{github.workspace}}/build/_deps/*-src
                  key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }}
                  restore-keys: |
                      ${{ env.cache-name }}-

            - name: Cache CMake dependency build objects
              uses: actions/cache@v4
              env:
                  cache-name: cache-cmake-dependency-builds
              with:
                  path: |
                      ${{github.workspace}}/build/_deps/*-build
                      ${{github.workspace}}/build/_deps/*-subbuild
                  key: ${{ env.cache-name }}-windows-latest-msvc-${{ hashFiles('**/CMakeLists.txt') }}
                  restore-keys: |
                      ${{ env.cache-name }}-windows-latest-msvc-

            - name: Download CMake
              uses: lukka/get-cmake@latest

            - name: Run CMake
              run: |
                  cmake -S./server-match -B./build
                  cmake --build ./build --config Release

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: server-match
                  path: |
                      ${{ github.workspace }}/build/bin/Release/server-match.exe
                      ${{ github.workspace }}/build/bin/Release/server-match.pdb
